theme: jekyll-theme-cayman
title: Katherine M. Kinnaird
description: 'Clare Boothe Luce Assistant Professor \n Department of Computer Science and Program in Statistical & Data Sciences \n Smith College'
